### ISSUE TITLE
Getting error message: cannot determine entry module ID

### ISSUE THREAD

**Issue by steelow** [gajus/isomorphic-webpack-demo#10]
Awesome work. Hopefully, I'm not too late to the party.  Anyway, whenever I tried to load the app in my browser, I get the following error:
`Error: Cannot determine entry module ID.
    at evalBundleCode (C:\jssandbox\isomorphic-webpack-demo\node_modules\isomorphic-webpack\dist\factories\createIsomorphicWebpack.js:134:13)
    at C:/jssandbox/isomorphic-webpack-demo/src/bin/server.js:62:30
    at Layer.handle [as handle_request] (C:\jssandbox\isomorphic-webpack-demo\node_modules\router\lib\layer.js:93:5)
    at next (C:\jssandbox\isomorphic-webpack-demo\node_modules\router\lib\route.js:144:13)
    at Route.dispatch (C:\jssandbox\isomorphic-webpack-demo\node_modules\router\lib\route.js:109:3)
    at handle (C:\jssandbox\isomorphic-webpack-demo\node_modules\router\index.js:520:11)
    at Layer.handle [as handle_request] (C:jssandbox\isomorphic-webpack-demo\node_modules\router\lib\layer.js:93:5)
    at C:\jssandbox\isomorphic-webpack-demo\node_modules\router\index.js:296:22
    at Function.process_params (C:\jssandbox\isomorphic-webpack-demo\node_modules\router\index.js:354:12)
    at next (C:\jssandbox\isomorphic-webpack-demo\node_modules\router\index.js:290:10)`

Any idea why?

**Comment by pedroBruno7** [comment]
I also have that issue. Can you help @gajus ?
I just do npm run start and it does not work (Windows)

**Comment by gajus** [comment]
There are so many better alternatives to isomorphic-webpack by now. No intention of reviving this project.
