### ISSUE TITLE
Getting "self is not defined" on start

### ISSUE THREAD

**Issue by leon-storm** [gajus/isomorphic-webpack-demo#4]
Hey!
I was checking out your demo, but stumbled on this issue quite fast after installation and running.

```
ReferenceError: self is not defined
    at isomorphic-webpack:195:30
    at isomorphic-webpack:190:47
    at module.exports (isomorphic-webpack:212:68)
    at Object.<anonymous> (isomorphic-webpack:440:36)
    at __webpack_require__ (isomorphic-webpack:20:30)
    at Object.<anonymous> (isomorphic-webpack:88:14)
    at __webpack_require__ (isomorphic-webpack:20:30)
    at evalBundleCode ([...]/isomorphic-webpack-demo/node_modules/isomorphic-webpack/dist/factories/createIsomorphicWebpack.js:141:12)
    at[...]/isomorphic-webpack-demo/src/bin/server.js:86:41
    at Layer.handle [as handle_request] ([...]/isomorphic-webpack-demo/node_modules/router/lib/layer.js:93:5)
```

Just fyi :)

**Comment by levity** [comment]
+1

**Comment by robstolarz** [comment]
#5 helped me debug this issue.
#6 solves it.

Once those ship, let me know if you run into any other trouble.

**Comment by glortho** [comment]
I'm having the same issue. Fixed it locally for now but is anything holding up the merge?
